DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS channels;
DROP TABLE IF EXISTS characters;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS list_clan;
DROP TABLE IF EXISTS list_friend;
DROP TABLE IF EXISTS list_quest;
